all: aigerImperative.cma aigerImperative.cmx aigerImperative.cmo

aigerImperative.cma:
	ocamlbuild -lib str aigerImperative.cma

aigerImperative.cmx:
	ocamlbuild -lib str  aigerImperative.cmx

aigerImperative.cmo:
	ocamlbuild -lib str  aigerImperative.cmo

clean: 
	ocamlbuild -clean



